### ISSUE TITLE
TypeError: Cannot read property 'code' of undefined [ESOCKETTIMEDOUT]

### ISSUE THREAD

**Issue by liberstein** [billylam/newman-reporter-testrail#13]
Hi!
My requests sometimes have not status code. It hapens because of network problems [ESOCKETTIMEDOUT]. After that your reporter is crashing:

`/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:127
                lastResult.comment = lastResult.comment.concat(`\n\nResponse: ${execution.response.code} ${execution.response.status}`);`

`TypeError: Cannot read property 'code' of undefined
    at execution.assertions.forEach (/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:127:100)
    at Array.forEach (<anonymous>)
    at executions.forEach (/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:107:30)
    at Array.forEach (<anonymous>)
    at TestRailReporter.handleTests (/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:105:16)
    at TestRailReporter.handleCompletion (/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:22:10)
    at EventEmitter.TestRailReporter.emitter.on (/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:17:12)
    at EventEmitter.emit (/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/eventemitter3/index.js:203:33)
    at PostmanCollectionRun.done (/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/newman/lib/run/index.js:291:29)
    at PostmanCollectionRun.triggers (/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/postman-runtime/lib/backpack/index.js:58:34)
    at /data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/postman-runtime/lib/backpack/index.js:163:29
    at PostmanCollectionRun._process (/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/postman-runtime/lib/runner/run.js:163:13)
    at PostmanCollectionRun.<anonymous> (/data/jenkins/workspace/s-partners_feature_DEVMTSRU-1213/test/api/node_modules/postman-runtime/lib/runner/run.js:169:76)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)`

I think you can change this behaviour, just add condition for response code. If ESOCKETTIMEDOUT  marked case as failure in TestRail.

**Comment by billylam** [comment]
Thanks, should be fixed with 1.0.17.  Reopen if you are still seeing issues.

https://github.com/billylam/newman-reporter-testrail/commit/f6657df982beb5be59600cd6add3091e1ae3a1dd
