### ISSUE TITLE
{"error":"Undefined index: HTTP_USER_AGENT"}

### ISSUE THREAD

**Issue by gregbakerstl** [billylam/newman-reporter-testrail#20]
Hello!
Google searches show others have had this issue, however in their case it was due to not using an APIKEY, which I am.

I am consistently receiving 500 errors with: 
Error: Server responded to https://testrail.foobar.com/index.php?/api/v2/add_run/foobar with status code 500:
{"error":"Undefined index: HTTP_USER_AGENT"}

I am exporting the following environment arguments without the redacted values:
	export TESTRAIL_DOMAIN='foobar';
	export TESTRAIL_USERNAME='foobar';
	export TESTRAIL_APIKEY='foobar';
	export TESTRAIL_PROJECTID='foobar';
	export TESTRAIL_TITLE="foobar"

Full stack dump below:

/usr/local/lib/node_modules/newman-reporter-testrail/node_modules/http-response-object/lib/index.js:51
            throw err;
            ^

Error: Server responded to https://testrail.charter.com/index.php?/api/v2/add_run/192 with status code 500:

{"error":"Undefined index: HTTP_USER_AGENT"}
    at Response.getBody (/usr/local/lib/node_modules/newman-reporter-testrail/node_modules/http-response-object/lib/index.js:41:23)
    at TestRailReporter.pushToTestrail (/usr/local/lib/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:252:64)
    at TestRailReporter.onComplete (/usr/local/lib/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:38:12)
    at EventEmitter.<anonymous> (/usr/local/lib/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:7:12)
    at EventEmitter.emit (/usr/local/lib/node_modules/newman/node_modules/eventemitter3/index.js:203:33)
    at done (/usr/local/lib/node_modules/newman/lib/run/index.js:293:29)
    at /usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/backpack/index.js:58:34
    at PostmanCollectionRun._process (/usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:163:13)
    at PostmanCollectionRun.<anonymous> (/usr/local/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:169:76)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7) {
  statusCode: 500,
  headers: {
    date: 'Wed, 29 Jul 2020 21:23:52 GMT',
    server: 'Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips PHP/7.2.18',
    'x-powered-by': 'PHP/7.2.18',
    'set-cookie': [ 'tr_session=ea57ad79-bdb7-46be-a9bc-591dfc6a0f56; HttpOnly' ],
    'content-length': '45',
    connection: 'close',
    'content-type': 'application/json; charset=utf-8'
  },
  body: Buffer(45) [Uint8Array] [
     10, 123, 34, 101, 114, 114, 111, 114,  34,
     58,  34, 85, 110, 100, 101, 102, 105, 110,
    101, 100, 32, 105, 110, 100, 101, 120,  58,
     32,  72, 84,  84,  80,  95,  85,  83,  69,
     82,  95, 65,  71,  69,  78,  84,  34, 125
  ],
  url: 'https://testrail.foobar.com/index.php?/api/v2/add_run/foobar'
}

**Comment by billylam** [comment]
I haven't seen this failure before.  Could you try to make the call using postman and see if you see the same issues?
https://www.gurock.com/testrail/docs/api/reference/runs

If that doesn't work can you also try passing in your password as the value of TESTRAIL_APIKEY?  Testrail accepts both for that field.

**Comment by billylam** [comment]
Try 1.0.26 of the reporter, which passes a user-agent on TestRail requests.  This is a shot in the dark, but without being able to reproduce it myself is my best guess.
