### ISSUE TITLE
"error":"Field :results cannot be empty but no valid tests or cases found"

### ISSUE THREAD

**Issue by juacuegut** [billylam/newman-reporter-testrail#29]
Hi there! 
I'm trying to put the results on testrail but I got this error "error":"Field :results cannot be empty but no valid tests or cases found".  The test run is successfully created and so the cases added are but I can no add results :(. Do you know what could be? I've tried a lot of things and I don't get it :(.

PruebaCollection

□ edificios Copy
└ /edificios/:idEdificio
  GET https://uat-sxapp.sinexia.es/sensedi/v1/salesforceapi/edificios/167 [200 OK, 744B, 416ms]
  √  C66875005 Status test
C:\Users\myuser\AppData\Roaming\npm\node_modules\newman-reporter-testrail-lite\node_modules\http-response-object\lib\index.js:51
            throw err;
            ^

Error: Server responded to https://axn-testrail01-p.axadmin.net/index.php?/api/v2/add_results_for_cases/305822 with status code 400:
{"error":"Field :results cannot be empty but no valid tests or cases found"}
    at Response.getBody (C:\Users\myuser\AppData\Roaming\npm\node_modules\newman-reporter-testrail-lite\node_modules\http-response-object\lib\index.js:41:23)
    at EventEmitter.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\newman-reporter-testrail-lite\lib\TestrailReporter.js:87:64)
    at EventEmitter.emit (C:\Users\myuser\AppData\Roaming\npm\node_modules\newman\node_modules\eventemitter3\index.js:203:33)
    at done (C:\Users\myuser\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:297:29)
    at C:\Users\myuser\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\backpack\index.js:58:34
    at PostmanCollectionRun._process (C:\Users\myuser\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:163:13)
    at PostmanCollectionRun.<anonymous> (C:\Users\myuser\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:169:76)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  statusCode: 400,
  headers: {
    date: 'Mon, 12 Apr 2021 12:17:31 GMT',
    server: 'Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.27',
    'x-powered-by': 'PHP/7.2.27',
    'set-cookie': [ 'tr_session=dcce395f-a32a-48f7-91ae-0efe24ad34d7; HttpOnly' ],
    'content-length': '76',
    connection: 'close',
    'content-type': 'application/json; charset=utf-8'
  },
  body: Buffer(76) [Uint8Array] [
    123,  34, 101, 114, 114, 111, 114,  34,  58,  34,  70, 105,
    101, 108, 100,  32,  58, 114, 101, 115, 117, 108, 116, 115,
     32,  99,  97, 110, 110, 111, 116,  32,  98, 101,  32, 101,
    109, 112, 116, 121,  32,  98, 117, 116,  32, 110, 111,  32,
    118,  97, 108, 105, 100,  32, 116, 101, 115, 116, 115,  32,
    111, 114,  32,  99,  97, 115, 101, 115,  32, 102, 111, 117,
    110, 100,  34, 125
  ],
  url: 'https://axn-testrail01-p.axadmin.net/index.php?/api/v2/add_results_for_cases/305822'
}

**Comment by billylam** [comment]
I think you are specifying the test number in the test name instead of the postman test.  In postman, your test should look something like 

```
pm.test("C66875005 Response time is less than 200ms", function () {
    pm.expect(pm.response.responseTime).to.be.below(200);
});
```

See also https://learning.postman.com/docs/writing-scripts/test-scripts/
