### ISSUE TITLE
I have used the TESTRAIL_RUNID as 'latest' then it is throwing the error

### ISSUE THREAD

**Issue by manoj-fsbtech** [billylam/newman-reporter-testrail#42]
Hi Team, 

When I have used the TESTRAIL_RUNID as 'latest' then it is throwing the error saying as 

/usr/lib/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:215
           runId = JSON.parse(response.getBody())[0].id;
                                                    ^

 TypeError: Cannot read property 'id' of undefined
     at TestRailReporter.pushToTestrail (/usr/lib/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:215:52)
     at TestRailReporter.onComplete (/usr/lib/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:33:12)
     at EventEmitter.<anonymous> (/usr/lib/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:12:12)
     at EventEmitter.emit (/usr/lib/node_modules/newman/node_modules/eventemitter3/index.js:203:33)
     at done (/usr/lib/node_modules/newman/lib/run/index.js:297:29)
     at /usr/lib/node_modules/newman/node_modules/postman-runtime/lib/backpack/index.js:58:34
     at PostmanCollectionRun._process (/usr/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:163:13)
     at PostmanCollectionRun.<anonymous> (/usr/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:169:76)
     at listOnTimeout (internal/timers.js:557:17)
     at processTimers (internal/timers.js:500:7)
     
I see the code saying as 
 let { runId } = this.env;
      if (runId) {
        // Get first run id from get_runs if latest specified
        if (this.env.runId.toLowerCase() === 'latest') {
          response = testRailApi.getRuns();
          **runId = JSON.parse(response.getBody())[0].id;**
        }
        response = testRailApi.getRun(runId);
      } else {
        // Add a new test run if no run id was specified
        response = testRailApi.addRun(title, this.results);
        runId = JSON.parse(response.getBody()).id;
      }
      
      
but we have the sample response for get_runs is below where ID is present in "runs".
{
  "offset": 0,
  "limit": 250,
  "size": 155,
  "_links": {
    "next": null,
    "prev": null
  },
  "runs": [
    {
      "id": 874,
      "suite_id": 156,
      "name": "Regression suite",
      "description": null,
      "milestone_id": null,
      "assignedto_id": null,
      "include_all": false,
      "is_completed": false,
      "completed_on": null,
      "config": null,.............

**Comment by billylam** [comment]
This should be fixed with the latest build.  Please give 1.0.44 a try and let me know if you continue to see issues.
