### ISSUE TITLE
500 error in Response.getBody

### ISSUE THREAD

**Issue by jkopko** [billylam/newman-reporter-testrail#59]
There is no indication of the issue, just a 500 error.
This does not always happen, it seems to be only some times, and perhaps only when the test run is larger in size.
Note there is not a 429 rate limit response, this is a 500.

Here's the stack trace, but with xxxxxxxx to replace my domain name.
/usr/lib/node_modules/newman-reporter-testrail/node_modules/http-response-object/lib/index.js:51
            throw err;
            ^
Error: Server responded to https://testrail.xxxxxxxx.com/index.php?/api/v2/add_results_for_cases/5713 with status code 500:
    at Response.getBody (/usr/lib/node_modules/newman-reporter-testrail/node_modules/http-response-object/lib/index.js:41:23)
    at TestRailApi.post (/usr/lib/node_modules/newman-reporter-testrail/lib/testRailApi.js:96:60)
    at TestRailApi.addResults (/usr/lib/node_modules/newman-reporter-testrail/lib/testRailApi.js:74:17)
    at TestRailReporter.pushToTestrail (/usr/lib/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:230:30)
    at TestRailReporter.onComplete (/usr/lib/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:33:12)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/newman-reporter-testrail/lib/TestrailReporter.js:12:12)
    at EventEmitter.emit (/usr/lib/node_modules/newman/node_modules/eventemitter3/index.js:203:33)
    at done (/usr/lib/node_modules/newman/lib/run/index.js:314:29)
    at /usr/lib/node_modules/newman/node_modules/postman-runtime/lib/backpack/index.js:58:34
    at PostmanCollectionRun._process (/usr/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:160:13)
    at PostmanCollectionRun.<anonymous> (/usr/lib/node_modules/newman/node_modules/postman-runtime/lib/runner/run.js:166:76)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7) {
  statusCode: 500,
  headers: {
    date: 'Tue, 16 May 2023 17:28:18 GMT',
    server: 'Apache/2.4.51 (Ubuntu)',
    'set-cookie': [
      'tr_session=3e137151-89a4-4936-8569-2fe7ad765f99; HttpOnly',
      'notificationbar=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/index'
    ],
    'content-length': '0',
    connection: 'close',
    'content-type': 'application/json; charset=utf-8'
  },
  body: Buffer(0) [Uint8Array] [],
  url: 'https://testrail.xxxxxxxx.com/index.php?/api/v2/add_results_for_cases/5713'
}

**Comment by dfranklin-at-bg** [comment]
I believe this can be resolved by using TESTRAIL_LOGGING=headers (or =none). Why the server responds with 500 instead of a 4xx, I don't know.

**Comment by billylam** [comment]
Thanks @dfranklin-at-bg !

@jkopko I would recommend trying the above first.  Originally this caused a 429 error, but something may have changed.

If this still doesn't fix your issue, I'd recommend adding a console.log to https://github.com/billylam/newman-reporter-testrail/blob/master/lib/testRailApi.js#L87 to log the post body (results), then trying the call yourself in postman.  You might get some insight that may help figure out what else may be going on and if a fix is needed.

**Comment by jkopko** [comment]
Confirmed! All good, thanks both.
