### ISSUE TITLE
{"error":"Field :results.elapsed is a required field."}

### ISSUE THREAD

**Issue by VBohdan** [billylam/newman-reporter-testrail#9]
Hi @billylam,
I faced with  a similar problem described here
https://github.com/billylam/newman-reporter-testrail/issues/1#event-1577179003

I am using the last version of module 1.0.12 but get an error
```
C:\Users\Ggiven\AppData\Roaming\npm\node_modules\newman-reporter-testrail\node_modules\http-response-object\lib\index.js:51
            throw err;
            ^

Error: Server responded to https://my.testrail.io/index.php?/api/v2/add_results_for_cases/312 with status code 400:
{"error":"Field :results.elapsed is a required field."}
```
```
    at Response.getBody (C:\Users\Ggiven\AppData\Roaming\npm\node_modules\newman-reporter-testrail\node_modules\http-response-object\lib\index.js:41:23)
    at TestRailReporter.handleCompletion (C:\Users\Ggiven\AppData\Roaming\npm\node_modules\newman-reporter-testrail\lib\TestrailReporter.js:93:62)
    at EventEmitter.<anonymous> (C:\Users\Ggiven\AppData\Roaming\npm\node_modules\newman-reporter-testrail\lib\TestrailReporter.js:17:12)
    at EventEmitter.emit (C:\Users\Ggiven\AppData\Roaming\npm\node_modules\newman\node_modules\eventemitter3\index.js:203:33)
    at done (C:\Users\Ggiven\AppData\Roaming\npm\node_modules\newman\lib\run\index.js:280:29)
    at C:\Users\Ggiven\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\backpack\index.js:58:34
    at PostmanCollectionRun._process (C:\Users\Ggiven\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:163:13)
    at PostmanCollectionRun.<anonymous> (C:\Users\Ggiven\AppData\Roaming\npm\node_modules\newman\node_modules\postman-runtime\lib\runner\run.js:169:76)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```
As a result I have a correct test run in TestRail but all cases marked as untested.

Any advice what I made wrong?
Thx

**Comment by billylam** [comment]
I suspect your admin has set elapsed as a required field.

If you have admin, can you confirm by clicking the administrations menu, then customizations, then the "elapsed" link and check if it's marked as required?

I'll see what options are available to fix this in the meantime.

**Comment by billylam** [comment]
I've just published 1.0.13 which adds elapsed time to testrail, give that a try once it shows up on https://www.npmjs.com/package/newman-reporter-testrail.  If you are still seeing any issues feel free to reopen.

**Comment by VBohdan** [comment]
Thx for response.

Yeah, we do have the “results” and “expired” fields marked as mandatory.
I guess everything will work if I turn them off.
But for estimation reasons (on the manual testing side mostly) to turn off "elapsed" field  probably not the best solution.
So, if the reporter could deal with such a case, it would be great
I don’t have enough knowledge in Node JS to do it myself
Thx

**Comment by VBohdan** [comment]
@billylam 
Now everything works fine.
Many thanks!
